#--------------------------------------------------------------
# Simple AWS CodeDeploy Config File
#
#--------------------------------------------------------------

version: 0.1
os     : windows
files:
  - source     : \
    destination: C:\