#--------------------------------------------------------------
# Simple AWS CodeDeploy Config File
#
#--------------------------------------------------------------

version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true
hooks:
  ApplicationStart:
    - location: ApplicationStartHook.sh
      timeout: 300
      runas: root